Update rollup's version to avoid error
package.json needs to be updated to avoid this error

Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd'
    at error ({your_path}/node_modules/rollup-stream/node_modules/rollup/dist/rollup.js:185:14)